name: deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      dir:
        required: true
        type: string
      host:
        required: true
        type: string
      port:
        required: true
        type: string
      user:
        required: true
        type: string
      key:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.dep-env }}

    steps:
    - uses: actions/checkout@v2

    - name: announce intentions
      run: echo deploying ${{ inputs.artifact-name }} to ${{ inputs.environment }}

